databases:
  - name:  coursera-postgresql-omrx
    databaseName: postgresql_iut1
    user: coursera_postgresql_user
    plan: starter

services:
  - type: web
    name: coursera-postgresql-omrx
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: coursera-postgresql
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4 # sensible default
