development:
 adapter: 'postgresql'
 encoding: 'unicode'
 database: 'postgresql'
 username: 'coursera_postgresql_user'
 url: 'postgresql://coursera_postgresql_user:KIWn4eCO6m5GJrKbOMGC4VHsXhwfaWDg@dpg-cqqjnfrv2p9s73b8nrkg-a/postgresql_iut1'
 password: 'KIWn4eCO6m5GJrKbOMGC4VHsXhwfaWDg'
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
 adapter: postgresql
 encoding: unicode
 database: postgresql
 username: coursera_postgresql_user
 url: <%= ENV['internal database'] %>
 password: <%= ENV['password'] %>
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
 adapter: 'postgresql'
 encoding: 'unicode'
 database: 'postgresql'
 username: 'coursera_postgresql_user'
 url: 'postgresql://coursera_postgresql_user:KIWn4eCO6m5GJrKbOMGC4VHsXhwfaWDg@dpg-cqqjnfrv2p9s73b8nrkg-a/postgresql_iut1'
 password: 'KIWn4eCO6m5GJrKbOMGC4VHsXhwfaWDg'
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


  
