development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: postgresql_iut1
  pool: 5
  username: coursera_postgresql_user
  password: KIWn4eCO6m5GJrKbOMGC4VHsXhwfaWDg
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: postgresql_iut1
  pool: 5
  username: coursera_postgresql_user
  password: KIWn4eCO6m5GJrKbOMGC4VHsXhwfaWDg
  host: localhost


production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: postgresql_iut1
  pool: 5
  username: coursera_postgresql_user
  password: KIWn4eCO6m5GJrKbOMGC4VHsXhwfaWDg
  host: dpg-cqqjnfrv2p9s73b8nrkg-a
