default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 'Hos$7500'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: suncalc_development

test:
  <<: *default
  database: suncalc_test

production:
  <<: *default
  database: suncalc_production
