development:
 adapter: 'postgresql'
 encoding: 'unicode'
 database: 'postgresql'
 username: 'coursera_postgresql_user'
 url: 'postgresql://coursera_postgresql_user:eUnn7zpPs2em4bTaj1NAAT7QM9oXDBIX@dpg-cqmm6btds78s73918e2g-a.oregon-postgres.render.com/coursera_postgresql'
 password: 'KIWn4eCO6m5GJrKbOMGC4VHsXhwfaWDg'
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
 adapter: postgresql
 encoding: unicode
 database: postgresql
 username: coursera_postgresql_user
 url: <%= ENV['internal database'] %>
 password: <%= ENV['password'] %>
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
 adapter: 'postgresql'
 encoding: 'unicode'
 database: 'postgresql'
 username: 'coursera_postgresql_user'
 url: 'postgresql://coursera_postgresql_user:eUnn7zpPs2em4bTaj1NAAT7QM9oXDBIX@dpg-cqmm6btds78s73918e2g-a.oregon-postgres.render.com/coursera_postgresql'
 password: 'KIWn4eCO6m5GJrKbOMGC4VHsXhwfaWDg'
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


  
