development:
  adapter: 'postgresql'
  encoding: 'unicode'
  database: 'postgresql_iut1'
  username: 'coursera_postgresql_user'
  password: 'KIWn4eCO6m5GJrKbOMGC4VHsXhwfaWDg'
  pool:  5 
  

test:
  adapter: 'postgresql'
  encoding: 'unicode'
  database: 'postgresql_iut1'
  username: 'coursera_postgresql_user'
  password: 'KIWn4eCO6m5GJrKbOMGC4VHsXhwfaWDg'
  pool:  5 

production:
  adapter: 'postgresql'
  encoding: 'unicode'
  database: 'postgresql_iut1'
  username: 'coursera_postgresql_user'
  password: 'KIWn4eCO6m5GJrKbOMGC4VHsXhwfaWDg'
  pool:  5 



  
