development:
 adapter: postgresql
  encoding: unicode
  database: postgresql_iut1
  username: coursera_postgresql_user
  url: <%= ENV['internal database'] %>
  password: <%= ENV['password'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  adapter: postgresql
  encoding: unicode
  database: postgresql_iut1
  username: coursera_postgresql_user
  url: <%= ENV['internal database'] %>
  password: <%= ENV['password'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  adapter: postgresql
  encoding: unicode
  database: postgresql_iut1
  username: coursera_postgresql_user
  url: <%= ENV['internal database'] %>
  password: <%= ENV['password'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


  
