default: &default
  adapter: postgresql
  encoding: unicode
  host: dpg-cqqjnfrv2p9s73b8nrkg-a
  username: coursera_postgresql_user
  password: KIWn4eCO6m5GJrKbOMGC4VHsXhwfaWDg
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: coursera_postgresql

test:
  <<: *default
  database: coursera_postgresql

production:
  <<: *default
  database: coursera_postgresql
